import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AllProviders from '@/components/AllProviders'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <AllProviders>
        <body className={inter.className}>
          <section className='flex min-h-screen flex-col items-center justify-between bg-[#FFEED9]'>
            <Navbar />
            {children}
          </section>
        </body>
        </AllProviders>
    </html>
  )
}
